### ISSUE TITLE
MLICENSE-132 integration test fails on Windows

### ISSUE THREAD

**Issue by ppalaga** [mojohaus/license-maven-plugin#204]
See https://ci.appveyor.com/project/ppalaga/license-maven-plugin-g0x55/builds/21547120/job/k2lp03sc6jror7lr

**Comment by gevegab** [comment]
The test actually fails on windows because the POM file has the following configuration 

```xml
 <licenseMergesUrl>file://${project.basedir}/licenses.merge</licenseMergesUrl>
```

and on windows this interpolates to a wrong URL (something like **file://c:\your\diretory/licenses.merge**)

Use instead:

```xml
 <licenseMergesUrl>${project.baseUri}licenses.merge</licenseMergesUrl>
```

I have build on windows with this modification and the test passes. 

But I have not tested on unix, please verify if this solves the problem
