### ISSUE TITLE
Load THIRD-PARTY.properties from parent POM

### ISSUE THREAD

**Issue by digulla** [mojohaus/license-maven-plugin#211]
I have a multi-module build with 5 modules. One of them is the parent POM (so I have a root POM and an independent parent POM).

The parent POM defines the Hibernate dependency which has a transitive dependency to dom4j. dom4j doesn't have a licence entry in it's POM.

This means I get a warning in each of the four modules about a missing license for dom4j: 

    [WARNING] There is 1 dependencies with no license :
    [WARNING]  - dom4j--dom4j--1.6.1

Right now, the only solution I found is to create `src/license/THIRD-PARTY.properties` in all four modules.

But now, this code is used in a bigger project with 20 modules. I'd rather avoid to have to copy this file all over the place.

Is there a better solution?

If not, would it be possible to load the `THIRD-PARTY.properties` from the parent POMs and merge those into the current project?
Or maybe we could at least define some missing licenses in the parent POM in the plugin config?

**Comment by digulla** [comment]
dom4j isn't an uncommon dependency. dom4j 2.0.x has a license element: http://central.maven.org/maven2/org/dom4j/dom4j/2.0.0/dom4j-2.0.0.pom
but dom4j 2.1.x doesn't even have a POM anymore: https://mvnrepository.com/artifact/org.dom4j/dom4j/2.1.1

**Comment by rez-** [comment]
Would be nice if we could add the missing licenses into the parent pom instead of defining a seperate file.

**Comment by digulla** [comment]
I'm using `license:aggregate-add-third-party`

**Comment by ppalaga** [comment]
Referencing a directory relative to the root or parent project is a common problem in Maven multimodule projects. I do not remember to have seen a Maven plugin that would solve it by itself. All plugins I know implement/recommend one of the following

(a) Package the config files to JARs that have to be declared as dependencies of the plugin in users's POM. Plugin them loads those files as classpath resources. This is basically what @digulla implemented in https://github.com/mojohaus/license-maven-plugin/pull/249 that was merged recently.

(b) Use [directory-maven-plugin](https://github.com/jdcasey/directory-maven-plugin) to define a pom.xml property that contains an absolute path to a specific project in the current build session. Such property can be used to construct an absolute path to THIRD-PARTY.properties that is the same in all reactor modules.

I do not think we can do more thus closing.

**Comment by nfalco79** [comment]
The directory-maven-plugin does not replace properties (also if executed in initialise phase) after maven has read and resolve the pom.xml (see [here](https://github.com/jdcasey/directory-maven-plugin/pull/6)) unless this behavior has changed (but and I think no).
Since Maven 3 you can use `${session.executionRootDirectory}` that unless you run mvn from a sub module to the work you expect (`${session.executionRootDirectory}/THIRD-PARTY.properties`

Anyway I had a make a test and look into the code and for `license:aggregate-add-third-party` it lookup the missingFile relative to all modules (and itself). This means that you can place in the parent project a src/license/THIRD-PARTY.properties and have effect on all submodules.

Maven parent project -> src/license/THIRD-PARTY.properties
`dom4j--dom4j--1.6.1=Dom license from missing file`

> [INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] License Test :: aggregate-add-third-party                          [pom]
[INFO] License Test :: aggregate-add-third-party - child 1                [jar]
[INFO] License Test :: aggregate-add-third-party - child 2                [jar]
[INFO] 
[INFO] ---< org.codehaus.mojo.license.test:test-aggregate-add-third-party >----
[INFO] Building License Test :: aggregate-add-third-party 1.18-SNAPSHOT   [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- license-maven-plugin:1.18-SNAPSHOT:aggregate-add-third-party (default-cli) @ test-aggregate-add-third-party ---
[INFO] Will check encoding : UTF-8
[WARNING] 
[WARNING] You should use *missingFile* parameter instead of deprecated *aggregateMissingLicensesFile*.
[WARNING] 
[INFO] After executing on 3 project(s)
[INFO] detected artifact commons-logging--commons-logging--1.1.1
[INFO] add dependency [commons-logging--commons-logging--1.1.1]
[INFO] Found 1 license(s) in module org.codehaus.mojo.license.test:test-aggregate-add-third-party-child1
[INFO] detected artifact xml-apis--xml-apis--1.0.b2
[INFO] add dependency [xml-apis--xml-apis--1.0.b2]
[INFO] detected artifact dom4j--dom4j--1.6.1
[INFO] add dependency [dom4j--dom4j--1.6.1]
[INFO] found 1 unsafe mappings
[INFO] Will use from missing file 1 dependencies :
 dom4j--dom4j--1.6.1 - 
[INFO] Found 2 license(s) in module org.codehaus.mojo.license.test:test-aggregate-add-third-party-child2
[INFO] 2 detected license(s).
[INFO]  - The Apache Software License, Version 2.0 for 2 artifact(s).
[INFO]  - Unknown license for 1 artifact(s).
[INFO] Use missing file path : src/license/THIRD-PARTY.properties
[INFO] Load missing file /Users/nikolasfalco/git/aggregate-add-third-party-simple/src/license/THIRD-PARTY.properties
[INFO] Writing third-party file to /Users/nikolasfalco/git/aggregate-add-third-party-simple/target/generated-sources/license/THIRD-PARTY.txt
[INFO] 
Lists of 3 third-party dependencies.
     (The Apache Software License, Version 2.0) Commons Logging (commons-logging:commons-logging:1.1.1 - http://commons.apache.org/logging)
     (Dom license from missing file) dom4j (dom4j:dom4j:1.6.1 - http://dom4j.org)
     (The Apache Software License, Version 2.0) XML Commons External Components XML APIs (xml-apis:xml-apis:1.0.b2 - http://xml.apache.org/commons/#external)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for License Test :: aggregate-add-third-party 1.18-SNAPSHOT:
[INFO] 
[INFO] License Test :: aggregate-add-third-party .......... SUCCESS [  1.098 s]
[INFO] License Test :: aggregate-add-third-party - child 1  SKIPPED
[INFO] License Test :: aggregate-add-third-party - child 2  SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.732 s
[INFO] Finished at: 2019-02-19T23:51:17+01:00
[INFO] ------------------------------------------------------------------------

**Comment by digulla** [comment]
The two options `overrideUrl` and `missingFileUrl` solve this issue for me.
I created a Maven project which just contains two text files. I add that project as a dependency to the *plugin* and then, I can reference the text files using `classpath:` URLs.

**Comment by duracotton** [comment]
Another solution using a central .properties file in combination a newer Maven variable has been found here: #382
