### ISSUE TITLE
Dependency exclusions with star * on groupId and artifactId not supported by plugin due to low version maven-artifact:2.2.1

### ISSUE THREAD

**Issue by Tibor17** [mojohaus/license-maven-plugin#218]
If a dependency ha an exclusion which is using `*` , this plugin take all transitive dependencies into account.
The reason is that property `mavenVersion` is `2.2.1`.

**Comment by ppalaga** [comment]
Please add steps to reproduce, ideally in from of an integration test under https://github.com/mojohaus/license-maven-plugin/tree/master/src/it

Which mojo(s) does this relate to?

**Comment by Tibor17** [comment]
We run the goal `aggregate-third-party-report`.
The point is that Maven artifact filter with stars `*` was first time introduced in Maven `3.3.1`. So this filtering artifact version should be used. We wanted to exclude all transitive dependencies on the dependency `org.wildfly:wildfly-cli`.

**Comment by ppalaga** [comment]
A fix incl. an integration test is welcome.

**Comment by nfalco79** [comment]
> If a dependency ha an exclusion which is using `*` , this plugin take all transitive dependencies into account.
> The reason is that property `mavenVersion` is `2.2.1`.

@Tibor17 is you refer to the includedGroups/excludedGroups pay attention because is not the usual MavenArtifact filters. It was implemented in a custom way and the excludedGroups value is interpreted as regular expression where the * has a different meaning.

To perform what you need should be re-implemented the way to filter where you can setup not only the filter on GAV with glob pattern (org.apache.maven.shared.artifact.filter.PatternExcludesArtifactFilter) but also the meaning of includeTransitiveDependencies that now, refers only to the direct dependencies of module in the reactor, and not to the transitive dependencies of excluded dependencies.

**Comment by ppalaga** [comment]
> interpreted as regular expression

I guess the `@Parameter` fields would deserve a better JavaDoc. Volunteers?

**Comment by ppalaga** [comment]
We improved the Javadoc in AbstractAddThirdPartyMojo in https://github.com/mojohaus/license-maven-plugin/commit/883a1ef47257b0d8da34ab4fd7025cdf98af13c4 
The same actually applies to AbstractThirdPartyReportMojo and AbstractDownloadLicensesMojo and we should eventually port the changes to these mojos too.

There is also a new param `artifactFiltersUrl` in all named mojos which allows for including/exluding artifacts based on `groupId:artifactId` regular expression patterns: https://github.com/mojohaus/license-maven-plugin/commit/459870d850a9d93c7acf8c1ed9fb971d768c67e7#diff-0bfb2b7e70b9abacb4339555c7b49e81R654

I guess the above covers what you need. Feel free to reopen in case it does not.
