### ISSUE TITLE
aggregate-add-third-party does not use missingFileUrl parameter

### ISSUE THREAD

**Issue by elballa** [mojohaus/license-maven-plugin#277]
Even though missingFileUrl is set and resolves missing license of a bundle project's dependency, the aggregate-add-third-party goal fails checking for license of that dependency.
I'll show you in an integration test

**Comment by ppalaga** [comment]
You may want to check https://github.com/mojohaus/license-maven-plugin/pull/246

**Comment by elballa** [comment]
Yes sure, the effect is the same but solution a little bit different

**Comment by nfalco79** [comment]
@ppalaga  My colleague has open a new defect instead reopen the other one for mistake.
He found the cause of the issue. The aggregate-add-third-party goal ignores missingFileUrl parameter if it is the only missing parameter specified.
There is a condition in AbstractAddThirdPartyMojo#resolveUnsafeDependenciesFromFile method that [check if the missingFile exists and is not empty](https://github.com/mojohaus/license-maven-plugin/blob/98e90b6399ca1295aa2b26ce9a510a4160a4bd82/src/main/java/org/codehaus/mojo/license/AbstractAddThirdPartyMojo.java#L808). If file (src/license/THIRD-PARTY.txt) exists and is not empty then he analyses missingFileUrl content otherwise this is ignored (and this is the bug).
