### ISSUE TITLE
Use slf4j over old logging APIs in Maven

### ISSUE THREAD

**Issue by digulla** [mojohaus/license-maven-plugin#337]
Change the code to use slf4j loggers everywhere.

Reasons:

- We have Mojo code which uses the Mojo logger
- We have other code which uses a Plexus logger
- We have code used from both places which would benefit from logging and jumps to hoops to make it happen.

If we used the underlying slf4j logging framework directly, every part of the code could use the same logger type and everyone could ask for a logger (right now, you have to have it injected via Plexus or call getLog() in the Mojo), eliminating the need to get loggers and then pass them around.

Changes: Get a logger using this code at the top of a class which needs logging:

    private final Logger LOG = LoggerFactory.getLogger( getClass() );

or using

    private static final Logger LOG = LoggerFactory.getLogger( TypeName.class );

Note: The latter is slightly faster but if you forget to replace the type name, the logger will have the wrong name.

Additional advantage: If you enable logger names in the log output, you can find places where some message was logged much more quickly.

**Comment by digulla** [comment]
Necessary to fix #201 
Without this, some methods will have too many parameters.

**Comment by digulla** [comment]
Please let me know if you'd accept a PR for this.

**Comment by ppalaga** [comment]
Sorry for the delay, I was travelling and had PTO in recent weeks.

Thanks for the proposal and for being ready to contribute. 

I agree with the idea and I prefer the `private static final` variant. 

Please use the place holders (`log.info("Processed {} resources", resourcesCount)`) rather than string concatenation (`log.info("Processed "+ resourcesCount +" resources")`)

The only issue I can think of related to this change is that this will potentially change the logger names for the existing log messages. I do not think it should prevent us from doing this. In the end, I'll bump the major with the next release for other reasons.
