### ISSUE TITLE
Apache like LICENSE file generation

### ISSUE THREAD

**Issue by solomax** [mojohaus/license-maven-plugin#44]
It would be extremely helpful if plugin will be able to generate LICENSE file like [1]

so there will be blocks like:
license name
affected libraries
license text

[1] https://git-wip-us.apache.org/repos/asf?p=tomee.git;a=blob_plain;f=LICENSE;hb=HEAD

**Comment by jieryn** [comment]
Plugin already does this, see here: http://www.mojohaus.org/license-maven-plugin/update-project-license-mojo.html

Please close this issue.

**Comment by solomax** [comment]
Hello @jieryn,
I might be not clear enough,  `mvn license:update-project-license -Dlicense.licenseName=apache_v2` will generate LICENSE.txt with selected licence text.

What I need is:
1) check all dependencies for my project (multimodule)
2) create the list of modules grouped by license
3) for each license generate block containing:
```
license name
affected libraries
license text
```

is it possible?

**Comment by jieryn** [comment]
Ok, your original link didn't include any third party license information at all. It was just the general LICENSE.txt text and didn't reference any dependencies at all. That is exactly why I gave you the `update-project-license` link.

I think what you are describing is generically possible. Check out http://www.mojohaus.org/license-maven-plugin/plugin-info.html to see the list of goals by this plugin. I think http://www.mojohaus.org/license-maven-plugin/third-party-report-mojo.html might capture everything you want, otherwise it would be a mixture of `aggregate-add-third-party` and `download-licenses` goals.

If none of these fit exactly what you are requesting, then I think it is unlikely that this plugin will be extended to provide that exact format.

**Comment by solomax** [comment]
Unfortunately I was unable to get the file I need using your plugin :(
This is why I'm handling this manually ...

will close the issue, thanks for your time
