### ISSUE TITLE
Global third party properties

### ISSUE THREAD

**Issue by viahl** [mojohaus/license-maven-plugin#71]
Proposal for Change.

After looking thru and working a little with the License plugin. There is a feature that is missing.
When working with a lot of different project, it is time consuming to maintain the THIRD_PARTY.txt.

It would be great if it would be possible to have an global static GLOBAL_THIRD_PARTY.properties that the plugin could 
read in. Which already have preconfig different plugins and which license they use. 

Today there is to many plugin that is slappy to reference to the right license file in a way that any good plugin could read.
For example Spring that doesn't include they license. Event thou they are Apache v2.

It should be possible to link to the GLOBAL_THIRD_PARTY.properties both with an File reference but also with an URL reference.
It is not so uncommon that larger organization or opensource project link to servers, instead to local files.

The format on the Global third party properties should be the same as the THIRD_PARTY.properties/THIRD_PARTY.txt file.

**Comment by tchemit** [comment]
Hi @viahl , this feature already exists :).

You can define a maven artifact with a missing third party file, and then expose it with type *license.properties***.

You can then include this dependency in the dependencies of the plugin.

I will close this issue since the solution exists. Call me back if you have any trouble while setting this up.
