### ISSUE TITLE
update-file-header changes file encoding

### ISSUE THREAD

**Issue by heapifyman** [mojohaus/license-maven-plugin#92]
We have a file in `UTF-8` encoding with special character German `ß` in javadoc.

We are using both Linux and Windows machines for development.

Everything works fine on Linux but when running `update-file-header` on a Windows machine, it changes the file encoding from `UTF-8` to Windows default, which screws up the `ß`, which in turn leads to a failure when creating the javadoc.

`license-maven-plugin` should respect the file's current encoding and not change it.

**Comment by tchemit** [comment]
@heapifyman , Ok I just fix it, I will deploy a snapshot can you check the fix is ok form you ?

**Comment by tchemit** [comment]
Snapshot 1.14-SNAPSHOT is ready to test :).

**Comment by maggu2810** [comment]
I am not using a Windows machine myself but some co-worker.
There is a degree character (`°`) in a source file.
Without the change (fd20eb4294c00b325cd1d422d2c942c678e96870) the plugin changes the character and the compiler will break because of an invalid UTF-8 encoding.
With the change (fd20eb4294c00b325cd1d422d2c942c678e96870) the plugin changes the character but the compiler does not complain an invalid UTF-8 encoding.
So, the encoding seems to be correct, but the character is changed to an invalid one.

Perhaps someone with an Windows machine could test.

**Comment by heapifyman** [comment]
@tchemit  Sorry for the late reply, I was on holidays.

Anyway, I just tested on a Windows machine and see the same behaviour as @maggu2810 :
with version 1.14-SNAPSHOT the build (and javadoc generation) succeeds but the character `ß` is still changed.
